import type { ClaimDetail } from "@/types/claimDetail";

// ─── Realistic mock claims dataset ──────────────────────────────────────────
export const MOCK_CLAIMS: ClaimDetail[] = [
  {
    id: "CLM-2024-001",
    claimNumber: "CLM-2024-001",
    status: "under_investigation",
    type: "auto_collision",
    priority: "high",
    incidentDate: "2024-09-12",
    filingDate: "2024-09-14",
    incidentLocation: "I-95 Northbound, Exit 42, Fort Lauderdale, FL",
    description:
      "Vehicle was struck from behind at highway speed while stopped in traffic. Airbags deployed. Both vehicles sustained significant damage. Police report filed on scene. Other driver admitted fault.",
    estimatedLoss: 18500,
    fraudRiskScore: 12,
    assignedAdjuster: "Sarah Mitchell",
    aiRecommendation: "auto_approve",
    aiConfidence: 87,
    createdAt: "2024-09-14T09:22:00Z",
    updatedAt: "2024-09-15T14:10:00Z",
    policyHolder: {
      id: "PH-001",
      name: "Marcus J. Rivera",
      policyNumber: "POL-FL-2021-88821",
      policyType: "Comprehensive Auto",
      coverageLimit: 50000,
      deductible: 500,
      effectiveDate: "2021-03-01",
      expiryDate: "2025-03-01",
      email: "m.rivera@email.com",
      phone: "(954) 555-0182",
      address: "4821 Coral Springs Dr, Fort Lauderdale, FL 33065",
    },
    documents: [
      { id: "DOC-001", claimId: "CLM-2024-001", fileName: "police_report_2024091201.pdf", fileSize: 245000, mimeType: "application/pdf", documentType: "police_report", uploadedAt: "2024-09-14T10:00:00Z", ocrProcessed: true, extractedText: "Incident report #FL-2024-091201. At approximately 14:32 hrs..." },
      { id: "DOC-002", claimId: "CLM-2024-001", fileName: "damage_front_bumper.jpg", fileSize: 3200000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-09-14T10:05:00Z", ocrProcessed: false },
      { id: "DOC-003", claimId: "CLM-2024-001", fileName: "repair_estimate_sunstate_auto.pdf", fileSize: 189000, mimeType: "application/pdf", documentType: "repair_estimate", uploadedAt: "2024-09-14T11:30:00Z", ocrProcessed: true, extractedText: "Total repair estimate: $18,450. Parts: $11,200. Labor: $7,250..." },
      { id: "DOC-004", claimId: "CLM-2024-001", fileName: "vehicle_front_damage.jpg", fileSize: 2800000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-09-14T10:06:00Z", ocrProcessed: false },
    ],
    anomalies: [
      { id: "ANO-001", type: "prior_claim", severity: "low", description: "Claimant filed 1 auto claim in the past 36 months (2022-11, $4,200 — resolved).", detectedBy: "Fraud Detector Agent", detectedAt: "2024-09-14T12:00:00Z", resolved: true },
    ],
    missingInfo: [],
    coverage: {
      policyNumber: "POL-FL-2021-88821",
      policyType: "Comprehensive Auto",
      coverageLimit: 50000,
      deductible: 500,
      isActive: true,
      expiryDate: "2025-03-01",
      coveredPerils: ["Collision", "Comprehensive", "Uninsured Motorist", "Medical Payments"],
      exclusions: ["Intentional damage", "Racing", "Commercial use"],
      priorClaims: 1,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Online portal submission", actor: "Marcus J. Rivera", status: "completed", timestamp: "2024-09-14T09:22:00Z" },
      { id: "T2", title: "AI Intake Validation", description: "Policy verified, coverage confirmed, documents indexed", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-09-14T09:23:00Z" },
      { id: "T3", title: "Fraud Risk Assessment", description: "Risk score: 12/100 — Low risk. Prior claim flagged and resolved.", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-09-14T12:05:00Z" },
      { id: "T4", title: "Damage Estimation", description: "AI cross-referencing repair estimate with market rates", actor: "Damage Estimator Agent", status: "active", timestamp: "2024-09-15T09:00:00Z" },
      { id: "T5", title: "Adjuster Review", description: "Pending damage estimation", actor: "Sarah Mitchell", status: "pending", timestamp: "" },
      { id: "T6", title: "Settlement Decision", description: "", actor: "System", status: "pending", timestamp: "" },
    ],
  },
  {
    id: "CLM-2024-002",
    claimNumber: "CLM-2024-002",
    status: "review_required",
    type: "property_damage",
    priority: "critical",
    incidentDate: "2024-09-08",
    filingDate: "2024-09-10",
    incidentLocation: "782 Magnolia Lane, Atlanta, GA 30301",
    description:
      "Hurricane-related flooding caused extensive water damage to first floor. Flooring, drywall, and appliances require full replacement. Mold remediation may be needed.",
    estimatedLoss: 67200,
    fraudRiskScore: 28,
    assignedAdjuster: "Thomas Okonkwo",
    aiRecommendation: "manual_review",
    aiConfidence: 74,
    createdAt: "2024-09-10T14:00:00Z",
    updatedAt: "2024-09-16T10:30:00Z",
    policyHolder: {
      id: "PH-002",
      name: "Eleanor & David Chen",
      policyNumber: "POL-GA-2019-44102",
      policyType: "Homeowners Premium",
      coverageLimit: 350000,
      deductible: 2500,
      effectiveDate: "2019-06-15",
      expiryDate: "2025-06-15",
      email: "d.chen@email.com",
      phone: "(404) 555-0239",
      address: "782 Magnolia Lane, Atlanta, GA 30301",
    },
    documents: [
      { id: "DOC-010", claimId: "CLM-2024-002", fileName: "flood_damage_living_room.jpg", fileSize: 4100000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-09-10T14:30:00Z", ocrProcessed: false },
      { id: "DOC-011", claimId: "CLM-2024-002", fileName: "restoration_quote_servepro.pdf", fileSize: 312000, mimeType: "application/pdf", documentType: "repair_estimate", uploadedAt: "2024-09-11T09:00:00Z", ocrProcessed: true, extractedText: "Water damage restoration estimate — Total: $67,200. Emergency water extraction: $4,500..." },
      { id: "DOC-012", claimId: "CLM-2024-002", fileName: "nws_flood_advisory_sep2024.pdf", fileSize: 95000, mimeType: "application/pdf", documentType: "other", uploadedAt: "2024-09-11T09:05:00Z", ocrProcessed: true },
    ],
    anomalies: [
      { id: "ANO-010", type: "prior_claim", severity: "medium", description: "Two prior property claims in past 5 years: 2021 ($12,400) and 2022 ($8,900).", detectedBy: "Fraud Detector Agent", detectedAt: "2024-09-10T15:00:00Z", resolved: false },
      { id: "ANO-011", type: "excessive_amount", severity: "medium", description: "Restoration estimate ($67,200) is 22% above median for similar flood events in the region.", detectedBy: "Damage Estimator Agent", detectedAt: "2024-09-11T11:00:00Z", resolved: false },
    ],
    missingInfo: [
      { id: "MI-001", field: "Mold Inspection Report", description: "Independent mold assessment required before remediation coverage can be determined.", required: true, requestedAt: "2024-09-12T09:00:00Z" },
    ],
    coverage: {
      policyNumber: "POL-GA-2019-44102",
      policyType: "Homeowners Premium",
      coverageLimit: 350000,
      deductible: 2500,
      isActive: true,
      expiryDate: "2025-06-15",
      coveredPerils: ["Fire", "Wind", "Hail", "Water Damage (sudden & accidental)", "Theft", "Liability"],
      exclusions: ["Flood (separate policy required)", "Earthquake", "Mold (if pre-existing)"],
      priorClaims: 2,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Phone submission via call center", actor: "Eleanor Chen", status: "completed", timestamp: "2024-09-10T14:00:00Z" },
      { id: "T2", title: "AI Intake Validation", description: "Policy active, flood endorsement confirmed", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-09-10T14:02:00Z" },
      { id: "T3", title: "Fraud Analysis", description: "Prior claims pattern flagged — medium risk", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-09-10T15:30:00Z" },
      { id: "T4", title: "Missing Information Requested", description: "Mold inspection report required", actor: "Thomas Okonkwo", status: "completed", timestamp: "2024-09-12T09:00:00Z" },
      { id: "T5", title: "Awaiting Adjuster Review", description: "Pending mold report and final damage assessment", actor: "Thomas Okonkwo", status: "active", timestamp: "2024-09-16T10:30:00Z" },
    ],
  },
  {
    id: "CLM-2024-003",
    claimNumber: "CLM-2024-003",
    status: "approved",
    type: "health_injury",
    priority: "medium",
    incidentDate: "2024-08-28",
    filingDate: "2024-08-30",
    incidentLocation: "Whole Foods Market, 2201 N Clybourn Ave, Chicago, IL",
    description:
      "Slip and fall on wet floor near produce section. No wet floor sign present. Sustained fractured left wrist, required ER visit and follow-up orthopedic care. 3 weeks partial disability.",
    estimatedLoss: 12800,
    approvedPayout: 11800,
    fraudRiskScore: 8,
    assignedAdjuster: "Priya Patel",
    aiRecommendation: "auto_approve",
    aiConfidence: 92,
    createdAt: "2024-08-30T08:45:00Z",
    updatedAt: "2024-09-06T16:00:00Z",
    policyHolder: {
      id: "PH-003",
      name: "James A. Whitfield",
      policyNumber: "POL-IL-2022-55901",
      policyType: "Personal Liability Plus",
      coverageLimit: 100000,
      deductible: 1000,
      effectiveDate: "2022-01-01",
      expiryDate: "2025-01-01",
      email: "j.whitfield@email.com",
      phone: "(312) 555-0091",
      address: "1140 W Fullerton Pkwy, Chicago, IL 60614",
    },
    documents: [
      { id: "DOC-020", claimId: "CLM-2024-003", fileName: "er_records_northwestern.pdf", fileSize: 580000, mimeType: "application/pdf", documentType: "medical_record", uploadedAt: "2024-08-30T09:00:00Z", ocrProcessed: true, extractedText: "Patient: James Whitfield. DX: Left distal radius fracture. Treatment: Closed reduction and splinting..." },
      { id: "DOC-021", claimId: "CLM-2024-003", fileName: "medical_bills_total.pdf", fileSize: 210000, mimeType: "application/pdf", documentType: "medical_record", uploadedAt: "2024-09-02T10:00:00Z", ocrProcessed: true },
      { id: "DOC-022", claimId: "CLM-2024-003", fileName: "incident_photo_store.jpg", fileSize: 1900000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-08-30T09:10:00Z", ocrProcessed: false },
    ],
    anomalies: [],
    missingInfo: [],
    coverage: {
      policyNumber: "POL-IL-2022-55901",
      policyType: "Personal Liability Plus",
      coverageLimit: 100000,
      deductible: 1000,
      isActive: true,
      expiryDate: "2025-01-01",
      coveredPerils: ["Medical Payments", "Personal Liability", "Bodily Injury"],
      exclusions: ["Intentional acts", "Business activities"],
      priorClaims: 0,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Mobile app submission", actor: "James Whitfield", status: "completed", timestamp: "2024-08-30T08:45:00Z" },
      { id: "T2", title: "AI Intake Validation", description: "All documents verified", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-08-30T08:46:00Z" },
      { id: "T3", title: "Fraud Risk Assessment", description: "Risk score: 8/100 — Low risk", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-08-30T09:00:00Z" },
      { id: "T4", title: "Medical Review", description: "Bills reconciled, $1,000 deductible applied", actor: "Damage Estimator Agent", status: "completed", timestamp: "2024-09-02T11:00:00Z" },
      { id: "T5", title: "Approved", description: "Auto-approved. Net payout: $11,800", actor: "Priya Patel", status: "completed", timestamp: "2024-09-06T16:00:00Z" },
    ],
  },
  {
    id: "CLM-2024-004",
    claimNumber: "CLM-2024-004",
    status: "submitted",
    type: "theft_loss",
    priority: "medium",
    incidentDate: "2024-09-18",
    filingDate: "2024-09-19",
    incidentLocation: "2847 Riverside Dr, Austin, TX 78741",
    description:
      "Vehicle broken into overnight. Stolen items include: MacBook Pro, camera equipment, gym bag. Window smashed on driver's side. Police report filed. Approx. $6,800 in personal property losses.",
    estimatedLoss: 6800,
    fraudRiskScore: 19,
    aiRecommendation: "further_investigation",
    aiConfidence: 61,
    createdAt: "2024-09-19T07:30:00Z",
    updatedAt: "2024-09-19T08:00:00Z",
    policyHolder: {
      id: "PH-004",
      name: "Aisha M. Thompson",
      policyNumber: "POL-TX-2023-77654",
      policyType: "Renters Premier",
      coverageLimit: 25000,
      deductible: 250,
      effectiveDate: "2023-04-01",
      expiryDate: "2025-04-01",
      email: "a.thompson@email.com",
      phone: "(512) 555-0312",
      address: "2847 Riverside Dr, Austin, TX 78741",
    },
    documents: [
      { id: "DOC-030", claimId: "CLM-2024-004", fileName: "police_report_austin_pd.pdf", fileSize: 178000, mimeType: "application/pdf", documentType: "police_report", uploadedAt: "2024-09-19T07:45:00Z", ocrProcessed: true },
      { id: "DOC-031", claimId: "CLM-2024-004", fileName: "broken_window.jpg", fileSize: 2100000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-09-19T07:50:00Z", ocrProcessed: false },
    ],
    anomalies: [
      { id: "ANO-020", type: "fraud_indicator", severity: "low", description: "No receipts or purchase records provided for high-value items (MacBook, camera). Investigation recommended.", detectedBy: "Fraud Detector Agent", detectedAt: "2024-09-19T08:00:00Z", resolved: false },
    ],
    missingInfo: [
      { id: "MI-010", field: "Purchase Receipts", description: "Proof of ownership for claimed stolen items valued above $500.", required: true, requestedAt: "2024-09-19T08:00:00Z" },
    ],
    coverage: {
      policyNumber: "POL-TX-2023-77654",
      policyType: "Renters Premier",
      coverageLimit: 25000,
      deductible: 250,
      isActive: true,
      expiryDate: "2025-04-01",
      coveredPerils: ["Theft", "Fire", "Water Damage", "Personal Liability"],
      exclusions: ["Vehicle theft (contents only)", "High-value jewelry (over $1,500 without rider)"],
      priorClaims: 0,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Web portal submission", actor: "Aisha Thompson", status: "completed", timestamp: "2024-09-19T07:30:00Z" },
      { id: "T2", title: "AI Intake Validation", description: "Policy active, coverage confirmed for theft", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-09-19T07:31:00Z" },
      { id: "T3", title: "Fraud Analysis Queued", description: "Pending receipts before full assessment", actor: "Fraud Detector Agent", status: "active", timestamp: "2024-09-19T08:00:00Z" },
    ],
  },
  {
    id: "CLM-2024-005",
    claimNumber: "CLM-2024-005",
    status: "assessment_pending",
    type: "commercial_liability",
    priority: "high",
    incidentDate: "2024-09-05",
    filingDate: "2024-09-07",
    incidentLocation: "Harbor View Restaurant, 301 Pier Ave, Boston, MA 02134",
    description:
      "Customer tripped over improperly secured outdoor signage during lunch service and sustained a knee injury requiring surgery. Customer is represented by legal counsel. Demand letter received for $145,000.",
    estimatedLoss: 145000,
    fraudRiskScore: 32,
    assignedAdjuster: "Robert Kwan",
    aiRecommendation: "manual_review",
    aiConfidence: 68,
    createdAt: "2024-09-07T11:00:00Z",
    updatedAt: "2024-09-16T14:00:00Z",
    policyHolder: {
      id: "PH-005",
      name: "Harbor View Hospitality LLC",
      policyNumber: "POL-MA-2020-COM-3310",
      policyType: "Commercial General Liability",
      coverageLimit: 1000000,
      deductible: 5000,
      effectiveDate: "2020-01-01",
      expiryDate: "2025-01-01",
      email: "owner@harborviewboston.com",
      phone: "(617) 555-0188",
      address: "301 Pier Ave, Boston, MA 02134",
    },
    documents: [
      { id: "DOC-040", claimId: "CLM-2024-005", fileName: "demand_letter_attorney.pdf", fileSize: 420000, mimeType: "application/pdf", documentType: "other", uploadedAt: "2024-09-07T11:30:00Z", ocrProcessed: true },
      { id: "DOC-041", claimId: "CLM-2024-005", fileName: "incident_report_internal.pdf", fileSize: 195000, mimeType: "application/pdf", documentType: "other", uploadedAt: "2024-09-07T11:30:00Z", ocrProcessed: true },
      { id: "DOC-042", claimId: "CLM-2024-005", fileName: "surgical_report_claimant.pdf", fileSize: 680000, mimeType: "application/pdf", documentType: "medical_record", uploadedAt: "2024-09-09T09:00:00Z", ocrProcessed: true },
    ],
    anomalies: [
      { id: "ANO-030", type: "excessive_amount", severity: "high", description: "Demand of $145,000 exceeds median for knee injury claims by 3.1x. Legal representation increases complexity.", detectedBy: "Damage Estimator Agent", detectedAt: "2024-09-08T10:00:00Z", resolved: false },
    ],
    missingInfo: [
      { id: "MI-020", field: "CCTV Footage", description: "Security camera footage from the time of incident requested from insured.", required: true, requestedAt: "2024-09-09T10:00:00Z" },
      { id: "MI-021", field: "Premises Liability Inspection", description: "Independent inspection of outdoor signage installation required.", required: false, requestedAt: "2024-09-09T10:00:00Z" },
    ],
    coverage: {
      policyNumber: "POL-MA-2020-COM-3310",
      policyType: "Commercial General Liability",
      coverageLimit: 1000000,
      deductible: 5000,
      isActive: true,
      expiryDate: "2025-01-01",
      coveredPerils: ["Bodily Injury", "Property Damage", "Personal Injury", "Advertising Injury"],
      exclusions: ["Employee injury (Workers Comp)", "Intentional acts", "Professional liability"],
      priorClaims: 1,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Attorney demand letter received", actor: "Harbor View Hospitality LLC", status: "completed", timestamp: "2024-09-07T11:00:00Z" },
      { id: "T2", title: "Legal Review Triggered", description: "Demand letter routed to legal team", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-09-07T11:05:00Z" },
      { id: "T3", title: "Liability Assessment", description: "Negligence indicators identified — escalated", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-09-08T10:00:00Z" },
      { id: "T4", title: "Missing Info Requested", description: "CCTV and premises inspection requested", actor: "Robert Kwan", status: "completed", timestamp: "2024-09-09T10:00:00Z" },
      { id: "T5", title: "Damage Assessment", description: "Awaiting independent assessment", actor: "Damage Estimator Agent", status: "active", timestamp: "2024-09-16T14:00:00Z" },
    ],
  },
  {
    id: "CLM-2024-006",
    claimNumber: "CLM-2024-006",
    status: "rejected",
    type: "auto_collision",
    priority: "low",
    incidentDate: "2024-08-15",
    filingDate: "2024-08-17",
    incidentLocation: "Private parking lot, Las Vegas, NV 89101",
    description:
      "Minor fender-bender in private parking lot. Claim submitted for $3,200 in damages.",
    estimatedLoss: 3200,
    fraudRiskScore: 71,
    assignedAdjuster: "Jennifer Adams",
    aiRecommendation: "reject",
    aiConfidence: 88,
    createdAt: "2024-08-17T13:00:00Z",
    updatedAt: "2024-08-22T09:00:00Z",
    policyHolder: {
      id: "PH-006",
      name: "Kevin D. Larson",
      policyNumber: "POL-NV-2023-11209",
      policyType: "Basic Auto",
      coverageLimit: 15000,
      deductible: 1000,
      effectiveDate: "2023-10-01",
      expiryDate: "2024-10-01",
      email: "k.larson@email.com",
      phone: "(702) 555-0441",
      address: "880 Paradise Rd, Las Vegas, NV 89101",
    },
    documents: [
      { id: "DOC-050", claimId: "CLM-2024-006", fileName: "damage_photo_1.jpg", fileSize: 980000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-08-17T13:30:00Z", ocrProcessed: false },
    ],
    anomalies: [
      { id: "ANO-040", type: "fraud_indicator", severity: "high", description: "Photo metadata indicates image taken 6 days before stated incident date. Likely pre-existing damage.", detectedBy: "Fraud Detector Agent", detectedAt: "2024-08-18T09:00:00Z", resolved: false },
      { id: "ANO-041", type: "prior_claim", severity: "high", description: "Three prior auto claims in 24 months for pre-existing or minor damage. Pattern consistent with fraud.", detectedBy: "Fraud Detector Agent", detectedAt: "2024-08-18T09:00:00Z", resolved: false },
    ],
    missingInfo: [],
    coverage: {
      policyNumber: "POL-NV-2023-11209",
      policyType: "Basic Auto",
      coverageLimit: 15000,
      deductible: 1000,
      isActive: true,
      expiryDate: "2024-10-01",
      coveredPerils: ["Collision", "Liability"],
      exclusions: ["Pre-existing damage", "Intentional damage"],
      priorClaims: 3,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "", actor: "Kevin Larson", status: "completed", timestamp: "2024-08-17T13:00:00Z" },
      { id: "T2", title: "Fraud Analysis", description: "Photo metadata anomaly detected", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-08-18T09:00:00Z" },
      { id: "T3", title: "Claim Rejected", description: "Pre-existing damage confirmed. Pattern fraud detected. Case referred to SIU.", actor: "Jennifer Adams", status: "error", timestamp: "2024-08-22T09:00:00Z" },
    ],
  },
  {
    id: "CLM-2024-007",
    claimNumber: "CLM-2024-007",
    status: "escalated",
    type: "property_damage",
    priority: "critical",
    incidentDate: "2024-09-01",
    filingDate: "2024-09-03",
    incidentLocation: "5502 Oak Creek Blvd, Houston, TX 77084",
    description:
      "Total house fire. Property completely destroyed. Family displaced. Structural total loss confirmed by fire department. Contents loss estimated at $95,000. Structure estimated at $310,000.",
    estimatedLoss: 405000,
    fraudRiskScore: 44,
    assignedAdjuster: "Marcus Webb",
    aiRecommendation: "manual_review",
    aiConfidence: 55,
    createdAt: "2024-09-03T08:00:00Z",
    updatedAt: "2024-09-17T16:00:00Z",
    policyHolder: {
      id: "PH-007",
      name: "Patricia & Gregory Nguyen",
      policyNumber: "POL-TX-2018-HO-9981",
      policyType: "Homeowners Deluxe",
      coverageLimit: 650000,
      deductible: 3000,
      effectiveDate: "2018-08-01",
      expiryDate: "2025-08-01",
      email: "p.nguyen@email.com",
      phone: "(832) 555-0774",
      address: "5502 Oak Creek Blvd, Houston, TX 77084",
    },
    documents: [
      { id: "DOC-060", claimId: "CLM-2024-007", fileName: "fire_dept_report_houston.pdf", fileSize: 520000, mimeType: "application/pdf", documentType: "police_report", uploadedAt: "2024-09-03T10:00:00Z", ocrProcessed: true },
      { id: "DOC-061", claimId: "CLM-2024-007", fileName: "aerial_drone_damage.jpg", fileSize: 5200000, mimeType: "image/jpeg", documentType: "photo", uploadedAt: "2024-09-04T09:00:00Z", ocrProcessed: false },
      { id: "DOC-062", claimId: "CLM-2024-007", fileName: "structural_assessment_engr.pdf", fileSize: 890000, mimeType: "application/pdf", documentType: "repair_estimate", uploadedAt: "2024-09-06T11:00:00Z", ocrProcessed: true },
    ],
    anomalies: [
      { id: "ANO-050", type: "fraud_indicator", severity: "high", description: "Fire originated in garage — arson not ruled out by fire department. Electrical fire origin listed as 'undetermined'.", detectedBy: "Fraud Detector Agent", detectedAt: "2024-09-04T09:00:00Z", resolved: false },
      { id: "ANO-051", type: "prior_claim", severity: "medium", description: "Policy increased coverage from $400,000 to $650,000 four months prior to fire.", detectedBy: "Policy Checker Agent", detectedAt: "2024-09-04T09:30:00Z", resolved: false },
    ],
    missingInfo: [
      { id: "MI-030", field: "Arson Investigation Report", description: "State Fire Marshal investigation report required before claim processing.", required: true, requestedAt: "2024-09-05T10:00:00Z" },
      { id: "MI-031", field: "Contents Inventory", description: "Detailed inventory of destroyed personal property with purchase records.", required: true, requestedAt: "2024-09-05T10:00:00Z" },
    ],
    coverage: {
      policyNumber: "POL-TX-2018-HO-9981",
      policyType: "Homeowners Deluxe",
      coverageLimit: 650000,
      deductible: 3000,
      isActive: true,
      expiryDate: "2025-08-01",
      coveredPerils: ["Fire", "Smoke", "Explosion", "Theft", "Liability", "Additional Living Expenses"],
      exclusions: ["Arson (by insured)", "Intentional acts"],
      priorClaims: 0,
    },
    timeline: [
      { id: "T1", title: "Claim Submitted", description: "Emergency submission via phone", actor: "Patricia Nguyen", status: "completed", timestamp: "2024-09-03T08:00:00Z" },
      { id: "T2", title: "ALE Coverage Activated", description: "Additional Living Expenses of $4,000/mo activated immediately", actor: "Intake Validator Agent", status: "completed", timestamp: "2024-09-03T08:30:00Z" },
      { id: "T3", title: "Arson Risk Flagged", description: "Fire origin undetermined — SIU review triggered", actor: "Fraud Detector Agent", status: "completed", timestamp: "2024-09-04T09:30:00Z" },
      { id: "T4", title: "SIU Investigation", description: "Special Investigations Unit assigned. Fire Marshal report pending.", actor: "Marcus Webb", status: "active", timestamp: "2024-09-17T16:00:00Z" },
    ],
  },
  {
    id: "CLM-2024-008",
    claimNumber: "CLM-2024-008",
    status: "draft",
    type: "auto_collision",
    priority: "low",
    incidentDate: "2024-09-20",
    filingDate: "2024-09-20",
    incidentLocation: "Oak Park Mall, 11149 W 95th St, Overland Park, KS",
    description: "Minor parking lot scrape. Exchanged information with other driver.",
    estimatedLoss: 1200,
    createdAt: "2024-09-20T17:00:00Z",
    updatedAt: "2024-09-20T17:00:00Z",
    policyHolder: {
      id: "PH-008",
      name: "Sandra K. Morrison",
      policyNumber: "POL-KS-2024-30291",
      policyType: "Standard Auto",
      coverageLimit: 20000,
      deductible: 500,
      effectiveDate: "2024-01-01",
      expiryDate: "2025-01-01",
      email: "s.morrison@email.com",
      phone: "(913) 555-0223",
      address: "2210 W 87th St, Overland Park, KS 66212",
    },
    documents: [],
    anomalies: [],
    missingInfo: [
      { id: "MI-040", field: "Police Report or Incident Form", description: "Required for all collision claims.", required: true, requestedAt: "2024-09-20T17:01:00Z" },
      { id: "MI-041", field: "Damage Photos", description: "Photos of all damaged areas required.", required: true, requestedAt: "2024-09-20T17:01:00Z" },
    ],
    coverage: {
      policyNumber: "POL-KS-2024-30291",
      policyType: "Standard Auto",
      coverageLimit: 20000,
      deductible: 500,
      isActive: true,
      expiryDate: "2025-01-01",
      coveredPerils: ["Collision", "Liability"],
      exclusions: ["Pre-existing damage"],
      priorClaims: 0,
    },
    timeline: [
      { id: "T1", title: "Draft Started", description: "Online portal — incomplete submission", actor: "Sandra Morrison", status: "active", timestamp: "2024-09-20T17:00:00Z" },
    ],
  },
];

export function getAllClaims(): ClaimDetail[] {
  return MOCK_CLAIMS;
}

export function getClaimById(id: string): ClaimDetail | undefined {
  return MOCK_CLAIMS.find((c) => c.id === id);
}

export function getDashboardStats() {
  const all = MOCK_CLAIMS;
  return {
    total:               all.length,
    underInvestigation:  all.filter((c) => c.status === "under_investigation").length,
    requiresInfo:        all.filter((c) => c.missingInfo.some((m) => !m.resolvedAt)).length,
    requiresReview:      all.filter((c) => c.status === "review_required" || c.status === "escalated").length,
    autoProcessed:       all.filter((c) => c.aiRecommendation === "auto_approve" && c.status === "approved").length,
    totalEstimatedLoss:  all.reduce((sum, c) => sum + c.estimatedLoss, 0),
    avgFraudScore:       Math.round(all.filter((c) => c.fraudRiskScore !== undefined).reduce((s, c) => s + (c.fraudRiskScore ?? 0), 0) / all.filter((c) => c.fraudRiskScore !== undefined).length),
  };
}
